# Inclure les routes du bundle ChrisScientistPlatformBundle
# et les préfixées par /platform
chris_scientist_platform:
    resource: "@ChrisScientistPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform
