# Ajouter annonce
chris_scientist_platform_add:
    path:     /add
    defaults: { _controller: ChrisScientistPlatformBundle:Advert:add }

# Accueil
chris_scientist_platform_home:
    path:     /{page}
    defaults:
        _controller: ChrisScientistPlatformBundle:Advert:index
        page: 1
    requirements:
        id: \d*

# Consulter annonce
chris_scientist_platform_view:
    path:     /advert/{id}
    defaults: { _controller: ChrisScientistPlatformBundle:Advert:view }
    requirements:
        id: \d+

# Modifier annonce
chris_scientist_platform_edit:
    path:     /edit/{id}
    defaults: { _controller: ChrisScientistPlatformBundle:Advert:edit }
    requirements:
        id: \d+

# Consulter annonce
chris_scientist_platform_delete:
    path:     /delete/{id}
    defaults: { _controller: ChrisScientistPlatformBundle:Advert:delete }
    requirements:
        id: \d+

