services:
    chris_scientist_platform.antispam:
        class: ChrisScientistPlatformBundle\Antispam\CSAntispam
        arguments: [@mailer, 10]
        tags:
            - { name: twig.extension }
        calls:
            - [ setLocale, [ %locale% ] ]
    chris_scientist_platform.doctrine.notification:
        class: ChrisScientistPlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer, %from_email%]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    chris_scientist_platform.beta.html:
        class: ChrisScientistPlatformBundle\Beta\BetaHTML
    chris_scientist_platform.beta.listener:
        class: ChrisScientistPlatformBundle\Beta\BetaListener
        arguments: [@chris_scientist_platform.beta.html, "2016-03-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
#    chris_scientist_platform.example:
#        class: ChrisScientistPlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
