services:
    chris_scientist_platform.antispam:
        class: ChrisScientistPlatformBundle\Antispam\CSAntispam
        arguments: [@mailer, %locale%, 10]
    chris_scientist_platform.doctrine.notification:
        class: ChrisScientistPlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer, %from_email%]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
#    chris_scientist_platform.example:
#        class: ChrisScientistPlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
